config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index' 

  resources 'students'
  resources 'videos'
   

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_attached_file :photo, 
	styles: {:small => "150x150>"}, 
		:url  => "/assets/students/:id/:style/:basename.:extension",
		default_url: "/images/:style/missing.png"

  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/




  	has_attached_file :video,
  		:styles => { :medium => { :geometry => "", :format => 'mp4' },
    	:thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10 }},
    	:processors => [:transcoder]

  	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
  	validates_attachment :video, size: {less_than: 130.megabytes}	
   
  
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	
	def index
		@student = Student.all
	end
	
	def create
		p student_params
		@student = Student.create(student_params)

		if @student.save
			redirect_to @student, notice: 'successful'
		else
			render 'new'
		end
	end    

	def show
		 @student = Student.find(params[:id])	
	end

 	def new 
	 	@student = Student.new
	end

	def edit
	end


	protected

	def student_params
		params.require(:student).permit(:name, :photo, :video)
	end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="container">

<div class="jumbotron">
<%= form_for @student, html: { multipart: true } do |form| %>

	<div class="field">
		<%= form.label :Name %></br>
		<%= form.text_field :name %>
	</div>
	<div class="field">
	<%= form.label :Photo %>
  <%= form.file_field :photo %><br/>
  </div>
  <div class="field">
  <%= form.label :Video %>
  <%= form.file_field :video %><br/>
  </div>
  <div class="action">
  <%= form.submit 'submit'%>
  </div>

<% end %>

</div>
</div>

app/views/students/edit.html.erb
<p>Edit form</p>

<%= render 'form' %>

<%= link_to 'show' , student_path %>

app/views/students/index.html.erb
<% @student.each do|s| %>
<p>
	<%= s.name %> | <%= image_tag(s.photo) %> | <%= image_tag(s.video)  %>	
</p>


<% end %>
<%= link_to 'new form', new_student_path  %>

app/views/students/new.html.erb
<%= render 'form'  %>

<%= link_to 'back', students_path %>

app/views/students/show.html.erb
<div class="container">
<div class="jumbotron">


	<%= @student.name %><br/>
  <%= image_tag @student.photo %>
  <%= video_tag @student.video %>
 

</div>
</div>