config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index' 

  resources 'students'
  resources 'videos'
   

end

app/models/video.rb
class Video < ActiveRecord::Base

	has_attached_file :video,
  		:styles => { :medium => { :geometry => "", :format => 'mp4' },
    	:thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10 }},
    	:processors => [:transcoder]

 	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
  validates_attachment :video, size: {less_than: 130.megabytes}	
   
  

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	

	def create
		@video = Video.create(video_params)
		if @video.save
			redirect_to @video
		else
			render 'new'
		end
	end
	

	def new
		@video = Video.new
	end 
	
	protected

	def video_params
		params.require(:video).permit(:description, :video)
	end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div class="container">

	<div class="jumbotron">

		<%= form_for @video, html: { multipart: true } do |form| %>

			<div class="field">
  			<%= form.label :Description %><br/>
  			<%= form.text_area :description %><br/>
  		</div>

  		<div class="field">
  			<%= form.label :Video %>
  			<%= form.file_field :video %><br/>
  		</div>

  		<div class="action">
  			<%= form.submit 'submit'%>
  		</div>

		<% end %>
	</div>
</div>	

app/views/videos/index.html.erb
<% @videos.each do|s| %>
<p>
	<%= s.description %> | <%= video_tag(s.video)  %>	
</p>


<% end %>
<%= link_to 'new form', new_video_path  %>

app/views/videos/new.html.erb
<%= render 'form', video: @video %>

<%= link_to 'back' , videos_path %>